// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rentchain/rentchain/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7759049f71d95c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7759049f71d95c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetRentalAgreementRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetRentalAgreementRequest) Reset()         { *m = QueryGetRentalAgreementRequest{} }
func (m *QueryGetRentalAgreementRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRentalAgreementRequest) ProtoMessage()    {}
func (*QueryGetRentalAgreementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7759049f71d95c, []int{2}
}
func (m *QueryGetRentalAgreementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRentalAgreementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRentalAgreementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRentalAgreementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRentalAgreementRequest.Merge(m, src)
}
func (m *QueryGetRentalAgreementRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRentalAgreementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRentalAgreementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRentalAgreementRequest proto.InternalMessageInfo

func (m *QueryGetRentalAgreementRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetRentalAgreementResponse struct {
	RentalAgreement RentalAgreement `protobuf:"bytes,1,opt,name=rentalAgreement,proto3" json:"rentalAgreement"`
}

func (m *QueryGetRentalAgreementResponse) Reset()         { *m = QueryGetRentalAgreementResponse{} }
func (m *QueryGetRentalAgreementResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRentalAgreementResponse) ProtoMessage()    {}
func (*QueryGetRentalAgreementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7759049f71d95c, []int{3}
}
func (m *QueryGetRentalAgreementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRentalAgreementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRentalAgreementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRentalAgreementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRentalAgreementResponse.Merge(m, src)
}
func (m *QueryGetRentalAgreementResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRentalAgreementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRentalAgreementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRentalAgreementResponse proto.InternalMessageInfo

func (m *QueryGetRentalAgreementResponse) GetRentalAgreement() RentalAgreement {
	if m != nil {
		return m.RentalAgreement
	}
	return RentalAgreement{}
}

type QueryAllRentalAgreementRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRentalAgreementRequest) Reset()         { *m = QueryAllRentalAgreementRequest{} }
func (m *QueryAllRentalAgreementRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRentalAgreementRequest) ProtoMessage()    {}
func (*QueryAllRentalAgreementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7759049f71d95c, []int{4}
}
func (m *QueryAllRentalAgreementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRentalAgreementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRentalAgreementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRentalAgreementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRentalAgreementRequest.Merge(m, src)
}
func (m *QueryAllRentalAgreementRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRentalAgreementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRentalAgreementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRentalAgreementRequest proto.InternalMessageInfo

func (m *QueryAllRentalAgreementRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRentalAgreementResponse struct {
	RentalAgreement []RentalAgreement   `protobuf:"bytes,1,rep,name=rentalAgreement,proto3" json:"rentalAgreement"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRentalAgreementResponse) Reset()         { *m = QueryAllRentalAgreementResponse{} }
func (m *QueryAllRentalAgreementResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRentalAgreementResponse) ProtoMessage()    {}
func (*QueryAllRentalAgreementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7759049f71d95c, []int{5}
}
func (m *QueryAllRentalAgreementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRentalAgreementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRentalAgreementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRentalAgreementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRentalAgreementResponse.Merge(m, src)
}
func (m *QueryAllRentalAgreementResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRentalAgreementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRentalAgreementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRentalAgreementResponse proto.InternalMessageInfo

func (m *QueryAllRentalAgreementResponse) GetRentalAgreement() []RentalAgreement {
	if m != nil {
		return m.RentalAgreement
	}
	return nil
}

func (m *QueryAllRentalAgreementResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "rentchain.rentchain.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "rentchain.rentchain.QueryParamsResponse")
	proto.RegisterType((*QueryGetRentalAgreementRequest)(nil), "rentchain.rentchain.QueryGetRentalAgreementRequest")
	proto.RegisterType((*QueryGetRentalAgreementResponse)(nil), "rentchain.rentchain.QueryGetRentalAgreementResponse")
	proto.RegisterType((*QueryAllRentalAgreementRequest)(nil), "rentchain.rentchain.QueryAllRentalAgreementRequest")
	proto.RegisterType((*QueryAllRentalAgreementResponse)(nil), "rentchain.rentchain.QueryAllRentalAgreementResponse")
}

func init() { proto.RegisterFile("rentchain/rentchain/query.proto", fileDescriptor_0b7759049f71d95c) }

var fileDescriptor_0b7759049f71d95c = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0xb5, 0x2d, 0x74, 0x3c, 0x14, 0xa7, 0x39, 0x48, 0x94, 0x4d, 0x59, 0xd4, 0x94,
	0x82, 0x33, 0xa6, 0x15, 0x8b, 0x17, 0x25, 0x39, 0x58, 0xf0, 0x54, 0x17, 0xbd, 0x78, 0x91, 0x49,
	0x7c, 0x4c, 0x16, 0x76, 0x67, 0xb6, 0xbb, 0x13, 0x6d, 0x11, 0x2f, 0x1e, 0xbd, 0x28, 0xf8, 0x25,
	0x3c, 0x7a, 0xf4, 0x22, 0x78, 0xec, 0xb1, 0xe0, 0xc5, 0x93, 0x48, 0x22, 0xf8, 0x35, 0x64, 0x67,
	0xc6, 0x34, 0x59, 0x77, 0x13, 0x8a, 0x97, 0xf0, 0x32, 0xfb, 0xde, 0xfb, 0xff, 0xfe, 0xfb, 0xde,
	0x2c, 0x6e, 0xa6, 0x20, 0x75, 0x7f, 0xc0, 0x43, 0xc9, 0xce, 0xa2, 0xc3, 0x21, 0xa4, 0xc7, 0x34,
	0x49, 0x95, 0x56, 0x64, 0x63, 0x72, 0x4c, 0x27, 0x51, 0xe3, 0x12, 0x8f, 0x43, 0xa9, 0x98, 0xf9,
	0xb5, 0x79, 0x8d, 0xba, 0x50, 0x42, 0x99, 0x90, 0xe5, 0x91, 0x3b, 0xbd, 0x2a, 0x94, 0x12, 0x11,
	0x30, 0x9e, 0x84, 0x8c, 0x4b, 0xa9, 0x34, 0xd7, 0xa1, 0x92, 0x99, 0x7b, 0xba, 0xdd, 0x57, 0x59,
	0xac, 0x32, 0xd6, 0xe3, 0x19, 0x58, 0x51, 0xf6, 0xa2, 0xdd, 0x03, 0xcd, 0xdb, 0x2c, 0xe1, 0x22,
	0x94, 0x26, 0xd9, 0xe5, 0x6e, 0x96, 0x81, 0x26, 0x3c, 0xe5, 0xf1, 0xa4, 0x5b, 0x59, 0x46, 0x1e,
	0xf1, 0xe8, 0x19, 0x17, 0x29, 0x40, 0x0c, 0x52, 0xdb, 0x5c, 0xbf, 0x8e, 0xc9, 0xa3, 0x5c, 0xef,
	0xc0, 0x34, 0x08, 0xe0, 0x70, 0x08, 0x99, 0xf6, 0x9f, 0xe0, 0x8d, 0x99, 0xd3, 0x2c, 0x51, 0x32,
	0x03, 0x72, 0x0f, 0xaf, 0x5a, 0xa1, 0xcb, 0x68, 0x13, 0x6d, 0x5d, 0xdc, 0xb9, 0x42, 0x4b, 0xde,
	0x09, 0xb5, 0x45, 0xdd, 0xb5, 0x93, 0x1f, 0xcd, 0xda, 0xc7, 0xdf, 0x9f, 0xb6, 0x51, 0xe0, 0xaa,
	0xfc, 0x3b, 0xd8, 0x33, 0x6d, 0xf7, 0x41, 0x07, 0x06, 0xa7, 0xf3, 0x97, 0xc6, 0x09, 0x93, 0x3a,
	0x5e, 0x09, 0xe5, 0x73, 0x38, 0x32, 0x02, 0x6b, 0x81, 0xfd, 0xe3, 0xbf, 0xc4, 0xcd, 0xca, 0x3a,
	0x87, 0xf6, 0x18, 0xaf, 0xa7, 0xb3, 0x8f, 0x1c, 0xe3, 0xb5, 0x52, 0xc6, 0x42, 0x9b, 0xee, 0x72,
	0x0e, 0x1b, 0x14, 0x5b, 0xf8, 0x03, 0x07, 0xdc, 0x89, 0xa2, 0x0a, 0xe0, 0x07, 0x18, 0x9f, 0x4d,
	0xc8, 0x49, 0xde, 0xa0, 0x76, 0x9c, 0x34, 0x1f, 0x27, 0xb5, 0x3b, 0xe4, 0xc6, 0x49, 0x0f, 0xb8,
	0x00, 0x57, 0x1b, 0x4c, 0x55, 0xfa, 0x5f, 0x91, 0xf3, 0x58, 0x26, 0x35, 0xcf, 0xe3, 0x85, 0xff,
	0xf4, 0x48, 0xf6, 0x67, 0x1c, 0x2c, 0x19, 0x07, 0xad, 0x85, 0x0e, 0x2c, 0xd2, 0xb4, 0x85, 0x9d,
	0x77, 0xcb, 0x78, 0xc5, 0x58, 0x20, 0x6f, 0x11, 0x5e, 0xb5, 0x5b, 0x40, 0x5a, 0xa5, 0x68, 0xff,
	0xae, 0x5c, 0x63, 0x6b, 0x71, 0xa2, 0xd5, 0xf4, 0x6f, 0xbe, 0xf9, 0xf6, 0xeb, 0xc3, 0x52, 0x8b,
	0x5c, 0x67, 0x42, 0x25, 0x03, 0x48, 0x43, 0x09, 0xac, 0xfa, 0x4e, 0x90, 0x2f, 0x08, 0xaf, 0x17,
	0x5e, 0x05, 0xd9, 0xad, 0x16, 0xab, 0xdc, 0xcd, 0xc6, 0xed, 0xf3, 0x15, 0x39, 0xda, 0xfb, 0x86,
	0xf6, 0x2e, 0xd9, 0x5b, 0x40, 0x5b, 0xbc, 0x9f, 0xec, 0x95, 0xd9, 0xfd, 0xd7, 0xe4, 0x33, 0xc2,
	0xa4, 0xd0, 0xbc, 0x13, 0x45, 0xf3, 0x2c, 0x54, 0x6e, 0xeb, 0x3c, 0x0b, 0xd5, 0x7b, 0xe7, 0xef,
	0x19, 0x0b, 0x6d, 0xc2, 0xce, 0x69, 0xa1, 0xfb, 0xf0, 0x64, 0xe4, 0xa1, 0xd3, 0x91, 0x87, 0x7e,
	0x8e, 0x3c, 0xf4, 0x7e, 0xec, 0xd5, 0x4e, 0xc7, 0x5e, 0xed, 0xfb, 0xd8, 0xab, 0x3d, 0xbd, 0x25,
	0x42, 0x3d, 0x18, 0xf6, 0x68, 0x5f, 0xc5, 0xa5, 0x4d, 0x8f, 0xa6, 0x62, 0x7d, 0x9c, 0x40, 0xd6,
	0x5b, 0x35, 0xdf, 0xab, 0xdd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xfc, 0x64, 0xc9, 0xa8,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of RentalAgreement items.
	RentalAgreement(ctx context.Context, in *QueryGetRentalAgreementRequest, opts ...grpc.CallOption) (*QueryGetRentalAgreementResponse, error)
	RentalAgreementAll(ctx context.Context, in *QueryAllRentalAgreementRequest, opts ...grpc.CallOption) (*QueryAllRentalAgreementResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/rentchain.rentchain.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RentalAgreement(ctx context.Context, in *QueryGetRentalAgreementRequest, opts ...grpc.CallOption) (*QueryGetRentalAgreementResponse, error) {
	out := new(QueryGetRentalAgreementResponse)
	err := c.cc.Invoke(ctx, "/rentchain.rentchain.Query/RentalAgreement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RentalAgreementAll(ctx context.Context, in *QueryAllRentalAgreementRequest, opts ...grpc.CallOption) (*QueryAllRentalAgreementResponse, error) {
	out := new(QueryAllRentalAgreementResponse)
	err := c.cc.Invoke(ctx, "/rentchain.rentchain.Query/RentalAgreementAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of RentalAgreement items.
	RentalAgreement(context.Context, *QueryGetRentalAgreementRequest) (*QueryGetRentalAgreementResponse, error)
	RentalAgreementAll(context.Context, *QueryAllRentalAgreementRequest) (*QueryAllRentalAgreementResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) RentalAgreement(ctx context.Context, req *QueryGetRentalAgreementRequest) (*QueryGetRentalAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RentalAgreement not implemented")
}
func (*UnimplementedQueryServer) RentalAgreementAll(ctx context.Context, req *QueryAllRentalAgreementRequest) (*QueryAllRentalAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RentalAgreementAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentchain.rentchain.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RentalAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRentalAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RentalAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentchain.rentchain.Query/RentalAgreement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RentalAgreement(ctx, req.(*QueryGetRentalAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RentalAgreementAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRentalAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RentalAgreementAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentchain.rentchain.Query/RentalAgreementAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RentalAgreementAll(ctx, req.(*QueryAllRentalAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rentchain.rentchain.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "RentalAgreement",
			Handler:    _Query_RentalAgreement_Handler,
		},
		{
			MethodName: "RentalAgreementAll",
			Handler:    _Query_RentalAgreementAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rentchain/rentchain/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetRentalAgreementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRentalAgreementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRentalAgreementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRentalAgreementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRentalAgreementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRentalAgreementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RentalAgreement.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllRentalAgreementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRentalAgreementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRentalAgreementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRentalAgreementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRentalAgreementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRentalAgreementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RentalAgreement) > 0 {
		for iNdEx := len(m.RentalAgreement) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RentalAgreement[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetRentalAgreementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRentalAgreementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RentalAgreement.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllRentalAgreementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRentalAgreementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RentalAgreement) > 0 {
		for _, e := range m.RentalAgreement {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRentalAgreementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRentalAgreementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRentalAgreementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRentalAgreementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRentalAgreementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRentalAgreementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RentalAgreement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RentalAgreement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRentalAgreementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRentalAgreementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRentalAgreementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRentalAgreementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRentalAgreementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRentalAgreementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RentalAgreement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RentalAgreement = append(m.RentalAgreement, RentalAgreement{})
			if err := m.RentalAgreement[len(m.RentalAgreement)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
