// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rentchain/rentchain/rental_agreement.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RentalAgreement struct {
	Index     string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ItemId    string `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	OwnerId   string `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	RenterId  string `protobuf:"bytes,4,opt,name=renterId,proto3" json:"renterId,omitempty"`
	Price     string `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	StartTime string `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Duration  string `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	IsActive  bool   `protobuf:"varint,8,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Creator   string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *RentalAgreement) Reset()         { *m = RentalAgreement{} }
func (m *RentalAgreement) String() string { return proto.CompactTextString(m) }
func (*RentalAgreement) ProtoMessage()    {}
func (*RentalAgreement) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f7cb341bf835ba, []int{0}
}
func (m *RentalAgreement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RentalAgreement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RentalAgreement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RentalAgreement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RentalAgreement.Merge(m, src)
}
func (m *RentalAgreement) XXX_Size() int {
	return m.Size()
}
func (m *RentalAgreement) XXX_DiscardUnknown() {
	xxx_messageInfo_RentalAgreement.DiscardUnknown(m)
}

var xxx_messageInfo_RentalAgreement proto.InternalMessageInfo

func (m *RentalAgreement) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *RentalAgreement) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *RentalAgreement) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *RentalAgreement) GetRenterId() string {
	if m != nil {
		return m.RenterId
	}
	return ""
}

func (m *RentalAgreement) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *RentalAgreement) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *RentalAgreement) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *RentalAgreement) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *RentalAgreement) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*RentalAgreement)(nil), "rentchain.rentchain.RentalAgreement")
}

func init() {
	proto.RegisterFile("rentchain/rentchain/rental_agreement.proto", fileDescriptor_c4f7cb341bf835ba)
}

var fileDescriptor_c4f7cb341bf835ba = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0xa0, 0x69, 0xe2, 0x05, 0xc9, 0x20, 0x64, 0x21, 0x64, 0x55, 0x4c, 0x15, 0x43,
	0x8a, 0xc4, 0x13, 0x94, 0xad, 0x8c, 0x11, 0x13, 0x0b, 0x72, 0x93, 0x53, 0x62, 0x89, 0xd8, 0x91,
	0x73, 0x85, 0xf2, 0x16, 0x3c, 0x16, 0x63, 0x47, 0x46, 0x94, 0x3c, 0x06, 0x0b, 0xb2, 0xd3, 0x84,
	0xb2, 0xfd, 0xdf, 0xfd, 0xbf, 0xee, 0x3f, 0x1d, 0xbd, 0xb1, 0xa0, 0x31, 0x2b, 0xa5, 0xd2, 0x8b,
	0xff, 0x4a, 0xbe, 0x3c, 0xcb, 0xc2, 0x02, 0x54, 0xa0, 0x31, 0xa9, 0xad, 0x41, 0xc3, 0xce, 0xc6,
	0x44, 0x32, 0xaa, 0xeb, 0x1f, 0x42, 0x4f, 0x53, 0x9f, 0x5f, 0x0e, 0x71, 0x76, 0x4e, 0x27, 0x4a,
	0xe7, 0xb0, 0xe5, 0x64, 0x46, 0xe6, 0x71, 0xda, 0x03, 0xbb, 0xa0, 0xa1, 0x42, 0xa8, 0x56, 0x39,
	0x3f, 0xf2, 0xe3, 0x3d, 0x31, 0x4e, 0xa7, 0xe6, 0x4d, 0x83, 0x5d, 0xe5, 0xfc, 0xd8, 0x1b, 0x03,
	0xb2, 0x4b, 0x1a, 0xb9, 0x22, 0x6f, 0x9d, 0x78, 0x6b, 0x64, 0xd7, 0x51, 0x5b, 0x95, 0x01, 0x9f,
	0xf4, 0x1d, 0x1e, 0xd8, 0x15, 0x8d, 0x1b, 0x94, 0x16, 0x1f, 0x55, 0x05, 0x3c, 0xf4, 0xce, 0xdf,
	0xc0, 0xed, 0xcb, 0x37, 0x56, 0xa2, 0x32, 0x9a, 0x4f, 0xfb, 0x7d, 0x03, 0x3b, 0x4f, 0x35, 0xcb,
	0x0c, 0xd5, 0x2b, 0xf0, 0x68, 0x46, 0xe6, 0x51, 0x3a, 0xb2, 0xbb, 0x30, 0xb3, 0x20, 0xd1, 0x58,
	0x1e, 0xf7, 0x17, 0xee, 0xf1, 0xfe, 0xe1, 0xb3, 0x15, 0x64, 0xd7, 0x0a, 0xf2, 0xdd, 0x0a, 0xf2,
	0xd1, 0x89, 0x60, 0xd7, 0x89, 0xe0, 0xab, 0x13, 0xc1, 0xd3, 0x6d, 0xa1, 0xb0, 0xdc, 0xac, 0x93,
	0xcc, 0x54, 0x8b, 0xc2, 0xd4, 0x25, 0x58, 0xa5, 0xe1, 0xe0, 0xc7, 0xdb, 0x03, 0x8d, 0xef, 0x35,
	0x34, 0xeb, 0xd0, 0x7f, 0xf9, 0xee, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xe1, 0xab, 0xec, 0x93,
	0x01, 0x00, 0x00,
}

func (m *RentalAgreement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RentalAgreement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RentalAgreement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintRentalAgreement(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.Duration) > 0 {
		i -= len(m.Duration)
		copy(dAtA[i:], m.Duration)
		i = encodeVarintRentalAgreement(dAtA, i, uint64(len(m.Duration)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.StartTime) > 0 {
		i -= len(m.StartTime)
		copy(dAtA[i:], m.StartTime)
		i = encodeVarintRentalAgreement(dAtA, i, uint64(len(m.StartTime)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintRentalAgreement(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RenterId) > 0 {
		i -= len(m.RenterId)
		copy(dAtA[i:], m.RenterId)
		i = encodeVarintRentalAgreement(dAtA, i, uint64(len(m.RenterId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OwnerId) > 0 {
		i -= len(m.OwnerId)
		copy(dAtA[i:], m.OwnerId)
		i = encodeVarintRentalAgreement(dAtA, i, uint64(len(m.OwnerId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ItemId) > 0 {
		i -= len(m.ItemId)
		copy(dAtA[i:], m.ItemId)
		i = encodeVarintRentalAgreement(dAtA, i, uint64(len(m.ItemId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintRentalAgreement(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRentalAgreement(dAtA []byte, offset int, v uint64) int {
	offset -= sovRentalAgreement(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RentalAgreement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovRentalAgreement(uint64(l))
	}
	l = len(m.ItemId)
	if l > 0 {
		n += 1 + l + sovRentalAgreement(uint64(l))
	}
	l = len(m.OwnerId)
	if l > 0 {
		n += 1 + l + sovRentalAgreement(uint64(l))
	}
	l = len(m.RenterId)
	if l > 0 {
		n += 1 + l + sovRentalAgreement(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovRentalAgreement(uint64(l))
	}
	l = len(m.StartTime)
	if l > 0 {
		n += 1 + l + sovRentalAgreement(uint64(l))
	}
	l = len(m.Duration)
	if l > 0 {
		n += 1 + l + sovRentalAgreement(uint64(l))
	}
	if m.IsActive {
		n += 2
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovRentalAgreement(uint64(l))
	}
	return n
}

func sovRentalAgreement(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRentalAgreement(x uint64) (n int) {
	return sovRentalAgreement(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RentalAgreement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRentalAgreement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RentalAgreement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RentalAgreement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ItemId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RenterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RenterId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Duration = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRentalAgreement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRentalAgreement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRentalAgreement(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRentalAgreement
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRentalAgreement
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRentalAgreement
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRentalAgreement
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRentalAgreement
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRentalAgreement        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRentalAgreement          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRentalAgreement = fmt.Errorf("proto: unexpected end of group")
)
