// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package rentchain

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_RentalAgreement           protoreflect.MessageDescriptor
	fd_RentalAgreement_index     protoreflect.FieldDescriptor
	fd_RentalAgreement_itemId    protoreflect.FieldDescriptor
	fd_RentalAgreement_ownerId   protoreflect.FieldDescriptor
	fd_RentalAgreement_renterId  protoreflect.FieldDescriptor
	fd_RentalAgreement_price     protoreflect.FieldDescriptor
	fd_RentalAgreement_startTime protoreflect.FieldDescriptor
	fd_RentalAgreement_duration  protoreflect.FieldDescriptor
	fd_RentalAgreement_isActive  protoreflect.FieldDescriptor
	fd_RentalAgreement_creator   protoreflect.FieldDescriptor
)

func init() {
	file_rentchain_rentchain_rental_agreement_proto_init()
	md_RentalAgreement = File_rentchain_rentchain_rental_agreement_proto.Messages().ByName("RentalAgreement")
	fd_RentalAgreement_index = md_RentalAgreement.Fields().ByName("index")
	fd_RentalAgreement_itemId = md_RentalAgreement.Fields().ByName("itemId")
	fd_RentalAgreement_ownerId = md_RentalAgreement.Fields().ByName("ownerId")
	fd_RentalAgreement_renterId = md_RentalAgreement.Fields().ByName("renterId")
	fd_RentalAgreement_price = md_RentalAgreement.Fields().ByName("price")
	fd_RentalAgreement_startTime = md_RentalAgreement.Fields().ByName("startTime")
	fd_RentalAgreement_duration = md_RentalAgreement.Fields().ByName("duration")
	fd_RentalAgreement_isActive = md_RentalAgreement.Fields().ByName("isActive")
	fd_RentalAgreement_creator = md_RentalAgreement.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_RentalAgreement)(nil)

type fastReflection_RentalAgreement RentalAgreement

func (x *RentalAgreement) ProtoReflect() protoreflect.Message {
	return (*fastReflection_RentalAgreement)(x)
}

func (x *RentalAgreement) slowProtoReflect() protoreflect.Message {
	mi := &file_rentchain_rentchain_rental_agreement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_RentalAgreement_messageType fastReflection_RentalAgreement_messageType
var _ protoreflect.MessageType = fastReflection_RentalAgreement_messageType{}

type fastReflection_RentalAgreement_messageType struct{}

func (x fastReflection_RentalAgreement_messageType) Zero() protoreflect.Message {
	return (*fastReflection_RentalAgreement)(nil)
}
func (x fastReflection_RentalAgreement_messageType) New() protoreflect.Message {
	return new(fastReflection_RentalAgreement)
}
func (x fastReflection_RentalAgreement_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_RentalAgreement
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_RentalAgreement) Descriptor() protoreflect.MessageDescriptor {
	return md_RentalAgreement
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_RentalAgreement) Type() protoreflect.MessageType {
	return _fastReflection_RentalAgreement_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_RentalAgreement) New() protoreflect.Message {
	return new(fastReflection_RentalAgreement)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_RentalAgreement) Interface() protoreflect.ProtoMessage {
	return (*RentalAgreement)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_RentalAgreement) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_RentalAgreement_index, value) {
			return
		}
	}
	if x.ItemId != "" {
		value := protoreflect.ValueOfString(x.ItemId)
		if !f(fd_RentalAgreement_itemId, value) {
			return
		}
	}
	if x.OwnerId != "" {
		value := protoreflect.ValueOfString(x.OwnerId)
		if !f(fd_RentalAgreement_ownerId, value) {
			return
		}
	}
	if x.RenterId != "" {
		value := protoreflect.ValueOfString(x.RenterId)
		if !f(fd_RentalAgreement_renterId, value) {
			return
		}
	}
	if x.Price != "" {
		value := protoreflect.ValueOfString(x.Price)
		if !f(fd_RentalAgreement_price, value) {
			return
		}
	}
	if x.StartTime != "" {
		value := protoreflect.ValueOfString(x.StartTime)
		if !f(fd_RentalAgreement_startTime, value) {
			return
		}
	}
	if x.Duration != "" {
		value := protoreflect.ValueOfString(x.Duration)
		if !f(fd_RentalAgreement_duration, value) {
			return
		}
	}
	if x.IsActive != false {
		value := protoreflect.ValueOfBool(x.IsActive)
		if !f(fd_RentalAgreement_isActive, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_RentalAgreement_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_RentalAgreement) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "rentchain.rentchain.RentalAgreement.index":
		return x.Index != ""
	case "rentchain.rentchain.RentalAgreement.itemId":
		return x.ItemId != ""
	case "rentchain.rentchain.RentalAgreement.ownerId":
		return x.OwnerId != ""
	case "rentchain.rentchain.RentalAgreement.renterId":
		return x.RenterId != ""
	case "rentchain.rentchain.RentalAgreement.price":
		return x.Price != ""
	case "rentchain.rentchain.RentalAgreement.startTime":
		return x.StartTime != ""
	case "rentchain.rentchain.RentalAgreement.duration":
		return x.Duration != ""
	case "rentchain.rentchain.RentalAgreement.isActive":
		return x.IsActive != false
	case "rentchain.rentchain.RentalAgreement.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rentchain.rentchain.RentalAgreement"))
		}
		panic(fmt.Errorf("message rentchain.rentchain.RentalAgreement does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_RentalAgreement) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "rentchain.rentchain.RentalAgreement.index":
		x.Index = ""
	case "rentchain.rentchain.RentalAgreement.itemId":
		x.ItemId = ""
	case "rentchain.rentchain.RentalAgreement.ownerId":
		x.OwnerId = ""
	case "rentchain.rentchain.RentalAgreement.renterId":
		x.RenterId = ""
	case "rentchain.rentchain.RentalAgreement.price":
		x.Price = ""
	case "rentchain.rentchain.RentalAgreement.startTime":
		x.StartTime = ""
	case "rentchain.rentchain.RentalAgreement.duration":
		x.Duration = ""
	case "rentchain.rentchain.RentalAgreement.isActive":
		x.IsActive = false
	case "rentchain.rentchain.RentalAgreement.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rentchain.rentchain.RentalAgreement"))
		}
		panic(fmt.Errorf("message rentchain.rentchain.RentalAgreement does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_RentalAgreement) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "rentchain.rentchain.RentalAgreement.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "rentchain.rentchain.RentalAgreement.itemId":
		value := x.ItemId
		return protoreflect.ValueOfString(value)
	case "rentchain.rentchain.RentalAgreement.ownerId":
		value := x.OwnerId
		return protoreflect.ValueOfString(value)
	case "rentchain.rentchain.RentalAgreement.renterId":
		value := x.RenterId
		return protoreflect.ValueOfString(value)
	case "rentchain.rentchain.RentalAgreement.price":
		value := x.Price
		return protoreflect.ValueOfString(value)
	case "rentchain.rentchain.RentalAgreement.startTime":
		value := x.StartTime
		return protoreflect.ValueOfString(value)
	case "rentchain.rentchain.RentalAgreement.duration":
		value := x.Duration
		return protoreflect.ValueOfString(value)
	case "rentchain.rentchain.RentalAgreement.isActive":
		value := x.IsActive
		return protoreflect.ValueOfBool(value)
	case "rentchain.rentchain.RentalAgreement.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rentchain.rentchain.RentalAgreement"))
		}
		panic(fmt.Errorf("message rentchain.rentchain.RentalAgreement does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_RentalAgreement) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "rentchain.rentchain.RentalAgreement.index":
		x.Index = value.Interface().(string)
	case "rentchain.rentchain.RentalAgreement.itemId":
		x.ItemId = value.Interface().(string)
	case "rentchain.rentchain.RentalAgreement.ownerId":
		x.OwnerId = value.Interface().(string)
	case "rentchain.rentchain.RentalAgreement.renterId":
		x.RenterId = value.Interface().(string)
	case "rentchain.rentchain.RentalAgreement.price":
		x.Price = value.Interface().(string)
	case "rentchain.rentchain.RentalAgreement.startTime":
		x.StartTime = value.Interface().(string)
	case "rentchain.rentchain.RentalAgreement.duration":
		x.Duration = value.Interface().(string)
	case "rentchain.rentchain.RentalAgreement.isActive":
		x.IsActive = value.Bool()
	case "rentchain.rentchain.RentalAgreement.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rentchain.rentchain.RentalAgreement"))
		}
		panic(fmt.Errorf("message rentchain.rentchain.RentalAgreement does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_RentalAgreement) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "rentchain.rentchain.RentalAgreement.index":
		panic(fmt.Errorf("field index of message rentchain.rentchain.RentalAgreement is not mutable"))
	case "rentchain.rentchain.RentalAgreement.itemId":
		panic(fmt.Errorf("field itemId of message rentchain.rentchain.RentalAgreement is not mutable"))
	case "rentchain.rentchain.RentalAgreement.ownerId":
		panic(fmt.Errorf("field ownerId of message rentchain.rentchain.RentalAgreement is not mutable"))
	case "rentchain.rentchain.RentalAgreement.renterId":
		panic(fmt.Errorf("field renterId of message rentchain.rentchain.RentalAgreement is not mutable"))
	case "rentchain.rentchain.RentalAgreement.price":
		panic(fmt.Errorf("field price of message rentchain.rentchain.RentalAgreement is not mutable"))
	case "rentchain.rentchain.RentalAgreement.startTime":
		panic(fmt.Errorf("field startTime of message rentchain.rentchain.RentalAgreement is not mutable"))
	case "rentchain.rentchain.RentalAgreement.duration":
		panic(fmt.Errorf("field duration of message rentchain.rentchain.RentalAgreement is not mutable"))
	case "rentchain.rentchain.RentalAgreement.isActive":
		panic(fmt.Errorf("field isActive of message rentchain.rentchain.RentalAgreement is not mutable"))
	case "rentchain.rentchain.RentalAgreement.creator":
		panic(fmt.Errorf("field creator of message rentchain.rentchain.RentalAgreement is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rentchain.rentchain.RentalAgreement"))
		}
		panic(fmt.Errorf("message rentchain.rentchain.RentalAgreement does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_RentalAgreement) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "rentchain.rentchain.RentalAgreement.index":
		return protoreflect.ValueOfString("")
	case "rentchain.rentchain.RentalAgreement.itemId":
		return protoreflect.ValueOfString("")
	case "rentchain.rentchain.RentalAgreement.ownerId":
		return protoreflect.ValueOfString("")
	case "rentchain.rentchain.RentalAgreement.renterId":
		return protoreflect.ValueOfString("")
	case "rentchain.rentchain.RentalAgreement.price":
		return protoreflect.ValueOfString("")
	case "rentchain.rentchain.RentalAgreement.startTime":
		return protoreflect.ValueOfString("")
	case "rentchain.rentchain.RentalAgreement.duration":
		return protoreflect.ValueOfString("")
	case "rentchain.rentchain.RentalAgreement.isActive":
		return protoreflect.ValueOfBool(false)
	case "rentchain.rentchain.RentalAgreement.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rentchain.rentchain.RentalAgreement"))
		}
		panic(fmt.Errorf("message rentchain.rentchain.RentalAgreement does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_RentalAgreement) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in rentchain.rentchain.RentalAgreement", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_RentalAgreement) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_RentalAgreement) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_RentalAgreement) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_RentalAgreement) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*RentalAgreement)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ItemId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OwnerId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.RenterId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Price)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.StartTime)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Duration)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.IsActive {
			n += 2
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*RentalAgreement)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x4a
		}
		if x.IsActive {
			i--
			if x.IsActive {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x40
		}
		if len(x.Duration) > 0 {
			i -= len(x.Duration)
			copy(dAtA[i:], x.Duration)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Duration)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.StartTime) > 0 {
			i -= len(x.StartTime)
			copy(dAtA[i:], x.StartTime)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StartTime)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.Price) > 0 {
			i -= len(x.Price)
			copy(dAtA[i:], x.Price)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Price)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.RenterId) > 0 {
			i -= len(x.RenterId)
			copy(dAtA[i:], x.RenterId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.RenterId)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.OwnerId) > 0 {
			i -= len(x.OwnerId)
			copy(dAtA[i:], x.OwnerId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OwnerId)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.ItemId) > 0 {
			i -= len(x.ItemId)
			copy(dAtA[i:], x.ItemId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ItemId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*RentalAgreement)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: RentalAgreement: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: RentalAgreement: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ItemId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ItemId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OwnerId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OwnerId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RenterId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.RenterId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Price = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StartTime = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Duration = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.IsActive = bool(v != 0)
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: rentchain/rentchain/rental_agreement.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RentalAgreement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ItemId    string `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	OwnerId   string `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	RenterId  string `protobuf:"bytes,4,opt,name=renterId,proto3" json:"renterId,omitempty"`
	Price     string `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	StartTime string `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Duration  string `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	IsActive  bool   `protobuf:"varint,8,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Creator   string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *RentalAgreement) Reset() {
	*x = RentalAgreement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rentchain_rentchain_rental_agreement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentalAgreement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalAgreement) ProtoMessage() {}

// Deprecated: Use RentalAgreement.ProtoReflect.Descriptor instead.
func (*RentalAgreement) Descriptor() ([]byte, []int) {
	return file_rentchain_rentchain_rental_agreement_proto_rawDescGZIP(), []int{0}
}

func (x *RentalAgreement) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *RentalAgreement) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RentalAgreement) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RentalAgreement) GetRenterId() string {
	if x != nil {
		return x.RenterId
	}
	return ""
}

func (x *RentalAgreement) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *RentalAgreement) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *RentalAgreement) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *RentalAgreement) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RentalAgreement) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_rentchain_rentchain_rental_agreement_proto protoreflect.FileDescriptor

var file_rentchain_rentchain_rental_agreement_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x72, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x72, 0x65, 0x6e, 0x74,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x67, 0x72,
	0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x72, 0x65,
	0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x22, 0xfb, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x41, 0x67, 0x72, 0x65,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42,
	0xc2, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x14, 0x52, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x24, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f,
	0x72, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xa2, 0x02, 0x03, 0x52, 0x52, 0x58, 0xaa,
	0x02, 0x13, 0x52, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x6e, 0x74,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0xca, 0x02, 0x13, 0x52, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x5c, 0x52, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xe2, 0x02, 0x1f, 0x52, 0x65,
	0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x52, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x14,
	0x52, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x52, 0x65, 0x6e, 0x74, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rentchain_rentchain_rental_agreement_proto_rawDescOnce sync.Once
	file_rentchain_rentchain_rental_agreement_proto_rawDescData = file_rentchain_rentchain_rental_agreement_proto_rawDesc
)

func file_rentchain_rentchain_rental_agreement_proto_rawDescGZIP() []byte {
	file_rentchain_rentchain_rental_agreement_proto_rawDescOnce.Do(func() {
		file_rentchain_rentchain_rental_agreement_proto_rawDescData = protoimpl.X.CompressGZIP(file_rentchain_rentchain_rental_agreement_proto_rawDescData)
	})
	return file_rentchain_rentchain_rental_agreement_proto_rawDescData
}

var file_rentchain_rentchain_rental_agreement_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rentchain_rentchain_rental_agreement_proto_goTypes = []interface{}{
	(*RentalAgreement)(nil), // 0: rentchain.rentchain.RentalAgreement
}
var file_rentchain_rentchain_rental_agreement_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rentchain_rentchain_rental_agreement_proto_init() }
func file_rentchain_rentchain_rental_agreement_proto_init() {
	if File_rentchain_rentchain_rental_agreement_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rentchain_rentchain_rental_agreement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentalAgreement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rentchain_rentchain_rental_agreement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rentchain_rentchain_rental_agreement_proto_goTypes,
		DependencyIndexes: file_rentchain_rentchain_rental_agreement_proto_depIdxs,
		MessageInfos:      file_rentchain_rentchain_rental_agreement_proto_msgTypes,
	}.Build()
	File_rentchain_rentchain_rental_agreement_proto = out.File
	file_rentchain_rentchain_rental_agreement_proto_rawDesc = nil
	file_rentchain_rentchain_rental_agreement_proto_goTypes = nil
	file_rentchain_rentchain_rental_agreement_proto_depIdxs = nil
}
